# Code Generated by Sidekick is for learning and experimentation purposes only.
import sys
import os
import re
import json
import logging
import difflib
import shutil
from typing import List, Dict, Any, Optional
from urllib.parse import urlparse
from decimal import Decimal

import pandas as pd
from datetime import datetime
from openai import OpenAI

# AWS imports
import boto3
from botocore.exceptions import ClientError

# AWS Glue imports
from awsglue.utils import getResolvedOptions

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# ============================================================================
# AWS HELPER FUNCTIONS
# ============================================================================

def is_s3_path(path: str) -> bool:
    """Check if the path is an S3 path."""
    return path.startswith('s3://') or path.startswith('s3a://')

def is_dynamodb_table(path: str) -> bool:
    """Check if the path refers to a DynamoDB table."""
    return path.startswith('dynamodb://') or path.startswith('dynamodb:')

def parse_s3_path(s3_path: str) -> tuple:
    """Parse S3 path to bucket and key."""
    parsed = urlparse(s3_path)
    bucket = parsed.netloc
    key = parsed.path.lstrip('/')
    return bucket, key

def parse_dynamodb_path(dynamo_path: str) -> str:
    """Parse DynamoDB path to get table name."""
    path = dynamo_path.replace('dynamodb://', '').replace('dynamodb:', '')
    return path

def read_from_s3(s3_path: str, local_path: str = None) -> str:
    """Download file from S3 to local temp location."""
    s3_client = boto3.client('s3')
    bucket, key = parse_s3_path(s3_path)
    
    if local_path is None:
        _, ext = os.path.splitext(key)
        local_path = f"/tmp/{os.path.basename(key)}"
    
    logger.info(f"Downloading from S3: s3://{bucket}/{key} to {local_path}")
    s3_client.download_file(bucket, key, local_path)
    return local_path

def write_to_s3(local_path: str, s3_path: str) -> None:
    """Upload file from local to S3."""
    s3_client = boto3.client('s3')
    bucket, key = parse_s3_path(s3_path)
    
    logger.info(f"Uploading to S3: {local_path} to s3://{bucket}/{key}")
    s3_client.upload_file(local_path, bucket, key)

def read_from_dynamodb(table_name: str, limit: int = None) -> pd.DataFrame:
    """Read data from DynamoDB table into pandas DataFrame."""
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table(table_name)
    
    logger.info(f"Scanning DynamoDB table: {table_name}")
    
    items = []
    scan_kwargs = {}
    if limit:
        scan_kwargs['Limit'] = limit
    
    try:
        response = table.scan(**scan_kwargs)
        items.extend(response.get('Items', []))
        
        if limit is None:
            while 'LastEvaluatedKey' in response:
                response = table.scan(ExclusiveStartKey=response['LastEvaluatedKey'])
                items.extend(response.get('Items', []))
        
        if not items:
            logger.warning(f"No items found in DynamoDB table: {table_name}")
            return pd.DataFrame()
        
        df = pd.DataFrame(items)
        logger.info(f"Read {len(df)} rows from DynamoDB table: {table_name}")
        return df
        
    except ClientError as e:
        logger.error(f"Error reading from DynamoDB: {e}")
        raise

def write_to_dynamodb(df: pd.DataFrame, table_name: str) -> None:
    """Write pandas DataFrame to DynamoDB table."""
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table(table_name)
    
    logger.info(f"Writing {len(df)} rows to DynamoDB table: {table_name}")
    
    items = df.to_dict('records')
    
    with table.batch_writer() as batch:
        for i, item in enumerate(items):
            cleaned_item = {k: ('' if pd.isna(v) else v) for k, v in item.items()}
            batch.put_item(Item=cleaned_item)
            
            if (i + 1) % 100 == 0:
                logger.info(f"Written {i + 1}/{len(items)} items to DynamoDB")
    
    logger.info(f"Successfully wrote all {len(items)} items to DynamoDB")

def get_dynamodb_schema(table_name: str) -> List[str]:
    """Get column names from DynamoDB table."""
    dynamodb = boto3.resource('dynamodb')
    table = dynamodb.Table(table_name)
    
    try:
        response = table.scan(Limit=1)
        items = response.get('Items', [])
        
        if not items:
            logger.warning(f"No items in DynamoDB table: {table_name}")
            return []
        
        return list(items[0].keys())
        
    except ClientError as e:
        logger.error(f"Error getting DynamoDB schema: {e}")
        raise

def load_config_from_s3(s3_path: str) -> dict:
    """Load JSON config file from S3."""
    local_path = read_from_s3(s3_path, "/tmp/config.json")
    with open(local_path, 'r', encoding='utf-8') as f:
        return json.load(f)

# ============================================================================
# CORE FUNCTIONS
# ============================================================================

# from decimal import Decimal
def convert_pandas_to_pyspark_dtype(pandas_dtype: str, sample_data: pd.Series = None) -> Dict[str, str]:
    """Convert pandas dtype to PySpark data type format."""
    dtype_lower = str(pandas_dtype).lower()

    # ------------------------------------------------------------
    # ADDITION: Handle DynamoDB import-from-S3 string values first
    # (minimal required enhancement for your project)
    # ------------------------------------------------------------
    if sample_data is not None:
        non_null = sample_data.dropna()

        if not non_null.empty:
            sample_vals = non_null.head(10).tolist()
            first_val = sample_vals[0]

            # Future-safe: if DynamoDB number comes as Decimal in some tables
            if isinstance(first_val, Decimal):
                has_fraction = any(
                    isinstance(v, Decimal) and v != v.to_integral_value()
                    for v in sample_vals
                )
                return {"data_type": "double" if has_fraction else "integer"}

            # Handle string values (your current DynamoDB import-from-S3 case)
            if isinstance(first_val, str):
                values = [str(v).strip() for v in sample_vals if v is not None]

                # Integer-like strings
                if values and all(re.match(r"^-?\d+$", v) for v in values):
                    return {"data_type": "integer"}

                # Float-like strings
                if values and all(re.match(r"^-?\d+(\.\d+)?$", v) for v in values):
                    return {"data_type": "double"}

                # Boolean-like strings
                lower_vals = {v.lower() for v in values}
                if lower_vals.issubset({"true", "false"}):
                    return {"data_type": "boolean"}

                # Timestamp format: YYYY-MM-DD HH:mm:ss
                if re.match(r'^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}(:\d{2})?$', values[0]):
                    return {"data_type": "timestamp", "date_format": "yyyy-MM-dd HH:mm:ss"}

                # Timestamp format: M/D/YYYY HH:mm:ss or MM/DD/YYYY HH:mm:ss
                if re.match(r'^\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}(:\d{2})?$', values[0]):
                    return {"data_type": "timestamp", "date_format": "M/d/yyyy HH:mm:ss"}

                # Date format: YYYY-MM-DD
                if re.match(r'^\d{4}-\d{2}-\d{2}$', values[0]):
                    try:
                        pd.to_datetime(values[:5], format='%Y-%m-%d', errors='raise')
                        return {"data_type": "date", "date_format": "yyyy-MM-dd"}
                    except:
                        pass

                # Date format: MM/DD/YYYY or M/D/YYYY
                if re.match(r'^\d{1,2}/\d{1,2}/\d{4}$', values[0]):
                    try:
                        pd.to_datetime(values[:5], format='%m/%d/%Y', errors='raise')
                        return {"data_type": "date", "date_format": "M/d/yyyy"}
                    except:
                        pass

    # ------------------------------------------------------------
    # EXISTING LOGIC (kept as-is)
    # ------------------------------------------------------------
    if sample_data is not None and pd.api.types.is_datetime64_any_dtype(sample_data):
        first_val = sample_data.dropna().iloc[0] if not sample_data.dropna().empty else None
        if first_val:
            date_str = str(first_val)
            if '/' in date_str:
                return {"data_type": "date", "date_format": "M/d/yyyy"}
            elif '-' in date_str:
                return {"data_type": "date", "date_format": "yyyy-MM-dd"}
        return {"data_type": "date"}

    if sample_data is not None and dtype_lower in ('object', 'string'):
        first_val = sample_data.dropna().iloc[0] if not sample_data.dropna().empty else None
        if first_val:
            date_str = str(first_val).strip()

            if re.match(r'^\d{1,2}/\d{1,2}/\d{4}', date_str):
                try:
                    pd.to_datetime(sample_data.head(5), format='%m/%d/%Y', errors='coerce')
                    return {"data_type": "date", "date_format": "M/d/yyyy"}
                except:
                    pass

            elif re.match(r'^\d{4}-\d{2}-\d{2}', date_str):
                try:
                    pd.to_datetime(sample_data.head(5), format='%Y-%m-%d', errors='coerce')
                    return {"data_type": "date", "date_format": "yyyy-MM-dd"}
                except:
                    pass

            elif re.match(r'^\d{2}-\d{2}-\d{4}', date_str):
                try:
                    pd.to_datetime(sample_data.head(5), format='%d-%m-%Y', errors='coerce')
                    return {"data_type": "date", "date_format": "dd-MM-yyyy"}
                except:
                    pass

            elif re.match(r'^\d{1,2}/\d{1,2}/\d{4}\s+\d{1,2}:\d{2}', date_str):
                return {"data_type": "timestamp", "date_format": "M/d/yyyy HH:mm:ss"}

            elif re.match(r'^\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}', date_str):
                return {"data_type": "timestamp", "date_format": "yyyy-MM-dd HH:mm:ss"}

    if 'bool' in dtype_lower:
        return {"data_type": "boolean"}

    if 'int64' in dtype_lower:
        return {"data_type": "integer"}
    elif 'int32' in dtype_lower or 'int' in dtype_lower:
        return {"data_type": "integer"}

    if 'float64' in dtype_lower:
        return {"data_type": "double"}
    elif 'float32' in dtype_lower:
        return {"data_type": "double"}

    return {"data_type": "string"}

def infer_schema(file_path: str, nrows: int = 100) -> List[Dict[str, Any]]:
    """Infer schema from data source."""
    
    if is_dynamodb_table(file_path):
        table_name = parse_dynamodb_path(file_path)
        df = read_from_dynamodb(table_name, limit=nrows)
        if df.empty:
            return []
    elif is_s3_path(file_path):
        local_path = read_from_s3(file_path)
        _, ext = os.path.splitext(local_path)
        ext = ext.lower()
        
        if ext == ".csv":
            df = pd.read_csv(local_path, nrows=nrows)
        elif ext in (".xlsx", ".xls"):
            df = pd.read_excel(local_path, nrows=nrows)
        elif ext == ".json":
            try:
                df = pd.read_json(local_path, orient="records", lines=False)
            except ValueError:
                df = pd.read_json(local_path, orient="records", lines=True)
            if nrows is not None:
                df = df.head(nrows)
        elif ext == ".parquet":
            df = pd.read_parquet(local_path)
            if nrows is not None:
                df = df.head(nrows)
        else:
            raise ValueError(f"Unsupported file type: {ext}")
    else:
        raise ValueError(f"Path must be S3 or DynamoDB: {file_path}")

    return [
        {
            "column": str(col),
            "dtype": str(df[col].dtype),
            "sample_data": df[col]
        }
        for col in df.columns
    ]

def save_json(obj: Any, output_path: str) -> None:
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
    logger.info("Wrote %s", output_path)

def generate_visual_diff(
    source_schema: List[Dict[str, str]],
    target_schema: List[Dict[str, str]],
    output_file: str = "schema_diff.html",
) -> None:
    src_cols = [c["column"] for c in source_schema]
    tgt_cols = [c["column"] for c in target_schema]

    html_content = difflib.HtmlDiff().make_file(
        src_cols, tgt_cols, fromdesc="Source Columns", todesc="Target Columns"
    )

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html_content)

    logger.info("Visual diff report generated: %s", output_file)

def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", s.lower())

def _sim(a: str, b: str) -> float:
    return difflib.SequenceMatcher(None, _norm(a), _norm(b)).ratio()

def llm_semantic_mapping(
    source_columns: List[str],
    target_columns: List[str],
    *,
    model: str = "gpt-4o",
) -> Dict[str, Optional[str]]:
    if not source_columns:
        return {}
    if not target_columns:
        return {s: None for s in source_columns}

    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY not set.")

    client = OpenAI(api_key=api_key)

    system = (
        "Return ONLY valid JSON. No markdown, no commentary.\n"
        "Output schema:\n"
        '{ "mapping": { "<source_col>": "<target_col_or_null>", ... } }\n'
        "Rules:\n"
        "- Each value must be one of the provided target columns or null.\n"
        "- Prefer semantic equivalence.\n"
        "- Use each target at most once when possible."
    )
    user = f"Source columns: {source_columns}\nTarget columns: {target_columns}"

    resp = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        response_format={"type": "json_object"},
        temperature=0,
    )

    data = json.loads(resp.choices[0].message.content or "{}")
    mapping = data.get("mapping", {})

    allowed = set(target_columns)
    cleaned: Dict[str, Optional[str]] = {}
    for src in source_columns:
        tgt = mapping.get(src, None)
        if tgt is None:
            cleaned[src] = None
        elif isinstance(tgt, str) and tgt in allowed:
            cleaned[src] = tgt
        else:
            cleaned[src] = None

    used = set()
    for src in source_columns:
        tgt = cleaned.get(src)
        if tgt is None:
            continue
        if tgt in used:
            cleaned[src] = None
        else:
            used.add(tgt)

    return cleaned

def generate_mapping(
    source_schema: List[Dict[str, Any]],
    target_schema: List[Dict[str, str]],
    *,
    model: str = "gpt-4o",
    strong_cutoff: float = 0.90,
) -> List[Dict[str, Any]]:

    source_info = {c["column"]: c for c in source_schema}
    target_columns = [c["column"] for c in target_schema]
    remaining_targets = set(target_columns)

    mapping: List[Dict[str, Any]] = []
    llm_sources: List[str] = []

    matched_targets = set()
    for src in source_schema:
        src_name = src["column"]
        src_data = source_info.get(src_name)
        
        type_info = convert_pandas_to_pyspark_dtype(
            src_data.get("dtype", "object"),
            src_data.get("sample_data")
        )

        best_tgt, best_score = None, -1.0
        for tgt in target_columns:
            score = _sim(src_name, tgt)
            if score > best_score:
                best_score, best_tgt = score, tgt

        if best_tgt is not None and best_score >= strong_cutoff and best_tgt not in matched_targets:
            mapping.append(
                {
                    "source_column": src_name,
                    "target_column": best_tgt,
                    "type": "one-to-one",
                    **type_info
                }
            )
            matched_targets.add(best_tgt)
            remaining_targets.discard(best_tgt)
        else:
            mapping.append(
                {
                    "source_column": src_name,
                    "target_column": None,
                    "type": "llm_required",
                    **type_info
                }
            )
            llm_sources.append(src_name)

    if llm_sources and remaining_targets:
        llm_result = llm_semantic_mapping(llm_sources, sorted(remaining_targets), model=model)

        used = set()
        for m in mapping:
            if m["type"] == "llm_required" and m["source_column"] in llm_result:
                suggested = llm_result[m["source_column"]]
                if suggested is not None and suggested in remaining_targets and suggested not in used:
                    m["target_column"] = suggested
                    m["type"] = "llm_one-to-one"
                    used.add(suggested)

        for m in mapping:
            if m["type"] == "llm_required" and m.get("target_column") is None:
                m["type"] = "unmapped_source"

        for t in used:
            remaining_targets.discard(t)

    for tgt in sorted(remaining_targets):
        mapping.append(
            {
                "source_column": None,
                "target_column": tgt,
                "type": "unmapped_target",
                "data_type": None,
            }
        )

    return mapping

def _read_columns_only(path: str) -> List[str]:
    """Read column names from data source."""
    if is_dynamodb_table(path):
        table_name = parse_dynamodb_path(path)
        return get_dynamodb_schema(table_name)
    
    if is_s3_path(path):
        local_path = read_from_s3(path)
        path = local_path
    
    _, ext = os.path.splitext(path)
    ext = ext.lower()
    if ext == ".csv":
        return list(pd.read_csv(path, nrows=0).columns)
    if ext in (".xlsx", ".xls"):
        return list(pd.read_excel(path, nrows=0).columns)
    if ext == ".json":
        try:
            df = pd.read_json(path, orient="records", lines=False)
        except ValueError:
            df = pd.read_json(path, orient="records", lines=True)
        return list(df.columns)
    if ext == ".parquet":
        df = pd.read_parquet(path)
        return list(df.columns)
    raise ValueError(f"Unsupported file type: {ext}")

def _read_df(path: str) -> pd.DataFrame:
    """Read DataFrame from data source."""
    if is_dynamodb_table(path):
        table_name = parse_dynamodb_path(path)
        return read_from_dynamodb(table_name)
    
    if is_s3_path(path):
        local_path = read_from_s3(path)
        path = local_path
    
    _, ext = os.path.splitext(path)
    ext = ext.lower()
    if ext == ".csv":
        return pd.read_csv(path)
    if ext in (".xlsx", ".xls"):
        return pd.read_excel(path)
    if ext == ".json":
        try:
            return pd.read_json(path, orient="records", lines=False)
        except ValueError:
            return pd.read_json(path, orient="records", lines=True)
    if ext == ".parquet":
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported file type: {ext}")

def _write_df(df: pd.DataFrame, path: str) -> None:
    """Write DataFrame to data source."""
    if is_dynamodb_table(path):
        table_name = parse_dynamodb_path(path)
        write_to_dynamodb(df, table_name)
        return
    
    if is_s3_path(path):
        _, ext = os.path.splitext(path)
        temp_path = f"/tmp/output{ext}"
        
        if ext.lower() == ".csv":
            df.to_csv(temp_path, index=False)
        elif ext.lower() in (".xlsx", ".xls"):
            df.to_excel(temp_path, index=False)
        elif ext.lower() == ".json":
            df.to_json(temp_path, orient="records", lines=False, force_ascii=False)
        elif ext.lower() == ".parquet":
            df.to_parquet(temp_path, index=False)
        else:
            raise ValueError(f"Unsupported file type: {ext}")
        
        write_to_s3(temp_path, path)
        return
    
    raise ValueError(f"Path must be S3 or DynamoDB: {path}")

def backfill_null_targets_in_mapping(mapping_path: str, target_path: str) -> bool:
    with open(mapping_path, 'r', encoding='utf-8') as f:
        mapping_json = json.load(f)
    
    if isinstance(mapping_json, dict) and "column_mappings" in mapping_json:
        mapping_list = mapping_json["column_mappings"]
        wrapper = mapping_json
    else:
        mapping_list = mapping_json
        wrapper = None

    if not isinstance(mapping_list, list):
        raise ValueError("mapping.json must be a list or an object with column_mappings")

    tgt_cols = set(_read_columns_only(target_path))
    changed = False

    for item in mapping_list:
        if not isinstance(item, dict):
            continue
        src = item.get("source_column")
        tgt = item.get("target_column")
        if src and tgt is None and src in tgt_cols:
            item["target_column"] = src
            changed = True

    if changed:
        if wrapper is not None:
            wrapper["column_mappings"] = mapping_list
            save_json(wrapper, mapping_path)
        else:
            save_json(mapping_list, mapping_path)

    return changed

def apply_mapping_to_target(source_path: str, target_path: str, mapping_path: str) -> str:
    """Apply mapping to transform target."""
    if is_dynamodb_table(target_path):
        logger.warning("Backup not created for DynamoDB table.")
        backup_path = None
    elif is_s3_path(target_path):
        bucket, key = parse_s3_path(target_path)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        root, ext = os.path.splitext(key)
        backup_key = f"{root}.bak_{ts}{ext}"
        backup_path = f"s3://{bucket}/{backup_key}"
        
        s3_client = boto3.client('s3')
        s3_client.copy_object(
            Bucket=bucket,
            CopySource={'Bucket': bucket, 'Key': key},
            Key=backup_key
        )
        logger.info(f"Created S3 backup: {backup_path}")
    else:
        backup_path = None

    source_cols = _read_columns_only(source_path)
    df_tgt = _read_df(target_path)

    with open(mapping_path, 'r', encoding='utf-8') as f:
        mapping_json = json.load(f)
    
    mapping_list = mapping_json["column_mappings"] if isinstance(mapping_json, dict) and "column_mappings" in mapping_json else mapping_json

    # rename_map: Dict[str, str] = {}
    # for item in mapping_list:
    #     src = item.get("source_column")
    #     tgt = item.get("target_column")
    #     if src and tgt:
    #         rename_map[tgt] = src

    # df_tgt = df_tgt.rename(columns={t: s for t, s in rename_map.items() if t in df_tgt.columns})

    fill_value = '' if is_dynamodb_table(target_path) else pd.NA

    for col in source_cols:
        if col not in df_tgt.columns:
            df_tgt[col] = fill_value

    extras = [c for c in df_tgt.columns if c not in source_cols]
    df_tgt = df_tgt.loc[:, list(source_cols) + extras]

    _write_df(df_tgt, target_path)
    backfill_null_targets_in_mapping(mapping_path, target_path)
    return backup_path

def load_primary_keys(config_path: str) -> List[Dict[str, str]]:
    """Load primary keys from S3 config."""
    if is_s3_path(config_path):
        data = load_config_from_s3(config_path)
    else:
        with open(config_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    
    # UPDATED: Read primary keys from master config -> common.primary_keys
    # Backward compatible with old config -> root level primary_keys
    pks = data.get("common", {}).get("primary_keys", data.get("primary_keys", []))
    
    if not isinstance(pks, list):
        raise ValueError("primary_keys must be a list")

    out: List[Dict[str, str]] = []
    for i, item in enumerate(pks):
        if not isinstance(item, dict):
            raise ValueError(f"primary_keys[{i}] must be an object")
        src = item.get("source_column")
        tgt = item.get("target_column")
        if not src or not tgt:
            raise ValueError(f"primary_keys[{i}] requires source_column and target_column")
        out.append({"source_column": str(src), "target_column": str(tgt)})
    return out

# ============================================================================
# MAIN FUNCTION FOR GLUE JOB
# ============================================================================

def main():
    """Main function for AWS Glue Job."""
    
    # Get Glue job parameters
    args = getResolvedOptions(sys.argv, [
        'source',
        'target',
        'openai_api_key',
        'primary_key_config',
        'output_s3_path',
        'model',
        'strong_cutoff',
        'apply_mapping'
    ])
    
    # Set OpenAI API key
    os.environ["OPENAI_API_KEY"] = args['openai_api_key']
    logger.info("OpenAI API key configured")
    
    # Parse parameters
    source = args['source']
    target = args['target']
    model = args.get('model', 'gpt-4o')
    strong_cutoff = float(args.get('strong_cutoff', '0.90'))
    apply_mapping_flag = args.get('apply_mapping', 'false').lower() == 'true'
    pk_config_path = args['primary_key_config']
    output_s3_path = args['output_s3_path']
    
    logger.info(f"Source: {source}")
    logger.info(f"Target: {target}")
    logger.info(f"Model: {model}")
    logger.info(f"Strong cutoff: {strong_cutoff}")
    logger.info(f"Apply mapping: {apply_mapping_flag}")
    
    # Infer schemas
    logger.info("Reading source schema...")
    source_schema = infer_schema(source)
    
    logger.info("Reading target schema...")
    target_schema = infer_schema(target)
    
    # Generate visual diff
    diff_report = "/tmp/schema_comparison.html"
    generate_visual_diff(source_schema, target_schema, diff_report)
    
    # Generate mapping
    logger.info("Generating column mappings...")
    mapping = generate_mapping(source_schema, target_schema, model=model, strong_cutoff=strong_cutoff)
    mapping_file = "/tmp/mapping.json"
    
    # Load primary keys
    logger.info(f"Loading primary keys from: {pk_config_path}")
    primary_keys = load_primary_keys(pk_config_path)
    
    # Save mapping
    mapping_json = {
        "primary_keys": primary_keys,
        "column_mappings": mapping,
    }
    save_json(mapping_json, mapping_file)
    
    # Upload outputs to S3
    s3_base = output_s3_path.rstrip('/')
    
    mapping_s3_path = f"{s3_base}/mapping.json"
    write_to_s3(mapping_file, mapping_s3_path)
    logger.info(f"Uploaded mapping to: {mapping_s3_path}")
    
    diff_s3_path = f"{s3_base}/schema_comparison.html"
    write_to_s3(diff_report, diff_s3_path)
    logger.info(f"Uploaded schema comparison to: {diff_s3_path}")
    
    # Apply mapping if requested
    if apply_mapping_flag:
        logger.info("Applying mapping to target...")
        backup = apply_mapping_to_target(source, target, mapping_file)
        if backup:
            logger.info(f"Target updated. Backup: {backup}")
        else:
            logger.info("Target updated. No backup created")
    
    logger.info("Job completed successfully!")

if __name__ == "__main__":
    main()
