import json
import os
from datetime import datetime
import pandas as pd
from pyspark.sql import functions as F
from pyspark.sql.functions import col
from pyspark.sql import SparkSession
from pyspark.sql.types import (
    StructType, StructField, StringType, IntegerType,
    DoubleType, BooleanType, DateType, TimestampType,
    LongType, ShortType, ByteType, ArrayType, MapType
)
from botocore.client import Config
from botocore.exceptions import ClientError



# ============================================================
# AWS GLUE IMPORTS
# ============================================================
import sys
import boto3
from urllib.parse import urlparse

from awsglue.utils import getResolvedOptions
from awsglue.context import GlueContext
from awsglue.dynamicframe import DynamicFrame
from awsglue.job import Job
from pyspark.context import SparkContext

# ============================================================
# CONFIGURATION (LOCAL DEFAULTS - USED ONLY FOR LOCAL RUN)
# ============================================================

SOURCE_PATH = "data/complex.json"           # Can be .csv, .json, .parquet, .xlsx
TARGET_PATH = "data/complex_target.json"    # Can be .csv, .json, .parquet, .xlsx OR dynamodb:table_name
MAPPING_PATH = "data/complex_mapping.json"
# SOURCE_PATH = "data/E-commerce-Source.csv"
# TARGET_PATH = "data/E-commerce-Target(1000records).json"
# MAPPING_PATH = "data/ecom_datatype_mapping.json"
RECONCILIATION_REPORT_PATH = "output/run_validation/validation_report.xlsx"
OUTPUT_BASE_PATH = "output/reconciliation"

# Overwrite options
OVERWRITE_ORIGINAL_TARGET = False
CREATE_BACKUP = True

# File format configurations (SAME AS YOUR VALIDATION SCRIPT)
FILE_CONFIG = {
    "source": {
        "multiline": True,
        "sheet_name": 0,
        "merge_schema": False
    },
    "target": {
        "multiline": True,
        "sheet_name": 0,
        "merge_schema": False
    }
}

# Code Generated by Sidekick is for learning and experimentation purposes only.

# Initialize S3 client with Signature Version 4 for KMS-encrypted buckets
s3_client = boto3.client(
    's3',
    config=Config(signature_version='s3v4')
)


# ============================================================
# AWS / S3 HELPER FUNCTIONS
# ============================================================
def is_s3_path(path):
    return str(path).startswith("s3://")


def parse_s3_path(s3_path):
    """
    Splits s3://bucket/key into (bucket, key)
    """
    parsed = urlparse(s3_path)
    bucket = parsed.netloc
    key = parsed.path.lstrip("/")
    return bucket, key


def ensure_s3_prefix_exists(s3_path):
    """
    No-op for S3 (folders are virtual), but kept for compatibility.
    """
    return


def create_run_output_dir_glue(base_output_dir):
    """
    Creates timestamped run folder path for S3 or local:
      <base_output_dir>/run_YYYYMMDD_HHMMSS
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # run_output_dir = f"{base_output_dir.rstrip('/')}/run_{timestamp}"
    run_output_dir = f"{base_output_dir.rstrip('/')}/run_reconciliation"

    # For local only, actually create directory
    if not is_s3_path(run_output_dir):
        os.makedirs(run_output_dir, exist_ok=True)

    return run_output_dir


def read_json_from_s3(s3_path):
    """
    Reads JSON file from S3 and returns dict
    """
    s3 = boto3.client("s3")
    bucket, key = parse_s3_path(s3_path)
    obj = s3.get_object(Bucket=bucket, Key=key)
    content = obj["Body"].read().decode("utf-8")
    return json.loads(content)


def write_bytes_to_s3(content_bytes, s3_path, content_type=None):
    """
    Uploads bytes content to S3
    """
    s3 = boto3.client("s3")
    bucket, key = parse_s3_path(s3_path)

    extra_args = {}
    if content_type:
        extra_args["ContentType"] = content_type

    s3.put_object(Bucket=bucket, Key=key, Body=content_bytes, **extra_args)
    print(f"[OK] Uploaded to S3: {s3_path}")

# ============================================================
# SPARK SESSION
# ============================================================
def create_spark_session(app_name="ETL Validation Job"):
    spark = (
        SparkSession.builder
        .appName(app_name)
        .master("local[*]")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("ERROR")
    return spark

# ============================================================
# GLUE CONTEXT / JOB INITIALIZER
# ============================================================
def create_glue_session(job_name="ETL Validation Job", args=None):
    """
    Creates GlueContext, SparkSession and Job for AWS Glue runtime.
    """
    sc = SparkContext.getOrCreate()
    glueContext = GlueContext(sc)
    spark = glueContext.spark_session
    spark.sparkContext.setLogLevel("ERROR")

    job = Job(glueContext)
    job.init(job_name, args if args else {})

    return glueContext, spark, job

# ============================================================
# FILE FORMAT DETECTION
# ============================================================
def detect_file_format(file_path):
    """
    Detects file format based on extension.
    """
    extension = file_path.lower().split('.')[-1]
    format_map = {
        'csv': 'csv',
        'json': 'json',
        'parquet': 'parquet',
        'xlsx': 'excel',
        'xls': 'excel'
    }
    detected_format = format_map.get(extension, None)

    if detected_format is None:
        raise ValueError(f"Unsupported file extension: {extension}")

    return detected_format



# ============================================================
# DYNAMODB HELPERS
# ============================================================
def is_dynamodb_path(path):
    """
    Detects whether a path is a DynamoDB table reference.
    Expected format:
      dynamodb:table_name
    """
    return isinstance(path, str) and path.startswith("dynamodb:")


def extract_dynamodb_table_name(path):
    """
    Extract DynamoDB table name from:
      dynamodb:table_name
    """
    return path.split("dynamodb:", 1)[1].strip()


def detect_input_format(path):
    """
    Detects input format for both files and DynamoDB references.
    """
    if is_dynamodb_path(path):
        return "dynamodb"
    return detect_file_format(path)
# ============================================================
# SCHEMA BUILDER FROM MAPPING
# ============================================================
def build_schema_from_mapping(column_mappings, dataset_name="source"):
    """
    Builds a PySpark StructType schema from mapping JSON.

    Args:
        column_mappings: List of column mapping dicts from JSON
        dataset_name: "source" or "target" - determines which column name to use

    Returns:
        StructType schema
    """
    type_map = {
        "string": StringType(),
        "integer": IntegerType(),
        "double": DoubleType(),
        "boolean": BooleanType(),
        "date": DateType(),
        "timestamp": TimestampType()
    }

    fields = []
    for mapping in column_mappings:
        # Choose column name based on dataset
        if dataset_name == "source":
            col_name = mapping["source_column"]
        else:
            col_name = mapping["target_column"]

        # Get data type from mapping, default to string if not specified
        data_type_str = mapping.get("data_type", "string")
        date_format = mapping.get("date_format")

        # KEY FIX: If date/timestamp has custom format, read as STRING first
        # We'll convert it to proper date/timestamp in apply_custom_date_formats()
        if data_type_str in ["date", "timestamp"] and date_format:
            # Read as string, will be converted later
            spark_type = StringType()
            print(f"[SCHEMA] {col_name}: Reading as STRING (will convert to {data_type_str} with format '{date_format}')")
        else:
            # Use normal type mapping
            spark_type = type_map.get(data_type_str, StringType())

        # All columns nullable by default
        fields.append(StructField(col_name, spark_type, True))

    return StructType(fields)

# ============================================================
# FILE READERS WITH SCHEMA SUPPORT
# ============================================================
def read_csv_with_schema(spark, file_path, schema):
    """
    Reads CSV with predefined schema (most efficient for CSV).
    """
    return (
        spark.read
        .schema(schema)
        .option("header", "true")
        .option("mode", "PERMISSIVE")  # Handle malformed records gracefully
        .csv(file_path)
    )


def read_json_with_schema(spark, file_path, schema=None, multiline=True):
    """
    Reads JSON file with optional schema enforcement.
    """
    reader = spark.read.option("multiLine", str(multiline).lower())

    if schema:
        reader = reader.schema(schema)
    else:
        reader = reader.option("inferSchema", "true")

    return reader.json(file_path)


def read_parquet_file(spark, file_path, merge_schema=False):
    """
    Reads Parquet file (uses embedded schema).
    """
    return (
        spark.read
        .option("mergeSchema", str(merge_schema).lower())
        .parquet(file_path)
    )


def read_excel_with_schema(spark, file_path, schema=None, sheet_name=0):
    """
    Reads Excel file using pandas, then converts to Spark DataFrame.
    Applies schema by casting columns if provided.
    Supports local path or S3 path.
    """
    local_file_path = file_path

    if is_s3_path(file_path):
        s3 = boto3.client("s3")
        bucket, key = parse_s3_path(file_path)
        local_file_path = f"/tmp/{os.path.basename(key)}"
        s3.download_file(bucket, key, local_file_path)
        print(f"[INFO] Downloaded Excel from S3 to: {local_file_path}")

    # Read Excel with pandas
    pandas_df = pd.read_excel(local_file_path, sheet_name=sheet_name)

    # Convert to Spark DataFrame
    spark_df = spark.createDataFrame(pandas_df)

    # Apply schema by casting columns if provided
    if schema:
        for field in schema.fields:
            if field.name in spark_df.columns:
                spark_df = spark_df.withColumn(
                    field.name,
                    F.col(field.name).cast(field.dataType)
                )

    return spark_df


def apply_custom_date_formats(df, column_mappings, dataset_name):
    """
    Applies custom date/timestamp format conversions after schema enforcement.
    This is needed when your mapping has custom date_format specifications.

    Args:
        df: Spark DataFrame
        column_mappings: List of column mapping dicts
        dataset_name: "source" or "target"

    Returns:
        DataFrame with custom date formats applied
    """
    for mapping in column_mappings:
        col_name = (mapping["source_column"] if dataset_name == "source"
                   else mapping["target_column"])

        data_type = mapping.get("data_type")
        date_format = mapping.get("date_format")

        # Only process if column exists in DataFrame
        if col_name not in df.columns:
            continue

        # Handle custom date format conversion
        if data_type == "date" and date_format:
            df = df.withColumn(
                col_name,
                F.when(
                    F.col(col_name).isNull() | (F.trim(F.col(col_name).cast("string")) == ""),
                    F.lit(None).cast("date")
                ).otherwise(
                    F.to_date(F.col(col_name), date_format)
                )
            )

        elif data_type == "timestamp" and date_format:
            df = df.withColumn(
                col_name,
                F.when(
                    F.col(col_name).isNull() | (F.trim(F.col(col_name).cast("string")) == ""),
                    F.lit(None).cast("timestamp")
                ).otherwise(
                    F.to_timestamp(F.col(col_name), date_format)
                )
            )

    return df


def read_file_smart(spark, file_path, column_mappings, dataset_name, **kwargs):
    """
    Smart file reader that chooses the best approach based on format.

    - CSV: Uses schema-at-read-time (most efficient)
    - JSON: Uses schema-at-read-time with custom date handling
    - Parquet: Uses embedded schema
    - Excel: Reads then applies schema

    Args:
        spark: SparkSession
        file_path: Path to file
        column_mappings: Column mappings from JSON
        dataset_name: "source" or "target"
        **kwargs: Format-specific options

    Returns:
        Spark DataFrame with enforced schema
    """
    file_format = detect_file_format(file_path)
    schema = build_schema_from_mapping(column_mappings, dataset_name)

    print(f"\n[INFO] Reading {dataset_name.upper()} file: {file_path}")
    print(f"[INFO] File format: {file_format.upper()}")
    print(f"[INFO] Using predefined schema from mapping JSON")

    # CSV: Most efficient with schema-at-read
    if file_format == 'csv':
        df = read_csv_with_schema(spark, file_path, schema)
        print_section("check")
        df.show()
        # Apply custom date formats if needed
        df = apply_custom_date_formats(df, column_mappings, dataset_name)
        return df

    # JSON: Schema-at-read with multiline support
    elif file_format == 'json':
        multiline = kwargs.get('multiline', True)
        df = read_json_with_schema(spark, file_path, schema, multiline)
        # Apply custom date formats if needed
        df = apply_custom_date_formats(df, column_mappings, dataset_name)
        return df

    # Parquet: Uses embedded schema
    elif file_format == 'parquet':
        merge_schema = kwargs.get('merge_schema', False)
        df = read_parquet_file(spark, file_path, merge_schema)
        # Cast columns to match expected schema
        df = cast_to_expected_schema(df, schema)
        return df

    # Excel: Read with pandas then apply schema
    elif file_format == 'excel':
        sheet_name = kwargs.get('sheet_name', 0)
        df = read_excel_with_schema(spark, file_path, schema, sheet_name)
        # Apply custom date formats if needed
        df = apply_custom_date_formats(df, column_mappings, dataset_name)
        return df

    else:
        raise ValueError(f"Unsupported file format: {file_format}")


def cast_to_expected_schema(df, expected_schema):
    """
    Casts DataFrame columns to match expected schema.
    Used for Parquet files which have embedded schemas.

    Args:
        df: Spark DataFrame
        expected_schema: StructType schema to match

    Returns:
        DataFrame with casted columns
    """
    for field in expected_schema.fields:
        if field.name in df.columns:
            df = df.withColumn(field.name, F.col(field.name).cast(field.dataType))

    return df


def read_mapping_json(mapping_path):
    """
    Reads mapping JSON from local file system.

    Expected format:
    {
      "primary_keys": [
        {"source_column": "...", "target_column": "..."}
      ],
      "column_mappings": [
        {
          "source_column": "...",
          "target_column": "...",
          "data_type": "string|integer|double|date|timestamp|boolean",  # Optional
          "date_format": "yyyy-MM-dd"  # Optional, required if data_type is date/timestamp
        }
      ]
    }
    """
    with open(mapping_path, "r") as f:
        mapping = json.load(f)

    primary_keys = mapping.get("primary_keys", [])
    column_mappings = mapping.get("column_mappings", [])

    if not primary_keys:
        raise ValueError("Mapping JSON must contain 'primary_keys'.")

    if not column_mappings:
        raise ValueError("Mapping JSON must contain 'column_mappings'.")

    # Validate data type specifications (if provided)
    valid_data_types = ["string", "integer", "double", "date", "timestamp", "boolean"]
    for mapping_entry in column_mappings:
        data_type = mapping_entry.get("data_type")

        if data_type:
            # Validate data type
            if data_type not in valid_data_types:
                raise ValueError(
                    f"Invalid data_type '{data_type}' for column '{mapping_entry.get('target_column')}'. "
                    f"Valid types: {valid_data_types}"
                )

            # Validate date_format for date/timestamp types
            if data_type in ["date", "timestamp"]:
                if not mapping_entry.get("date_format"):
                    raise ValueError(
                        f"Column '{mapping_entry.get('target_column')}' has data_type '{data_type}' "
                        f"but missing 'date_format' specification."
                    )

    return primary_keys, column_mappings

# ============================================================
# GLUE-SAFE MAPPING READER
# ============================================================
def read_mapping_json_glue(mapping_path):
    """
    Reads mapping JSON from local file system OR S3.
    Same validation logic as read_mapping_json().
    """
    if is_s3_path(mapping_path):
        mapping = read_json_from_s3(mapping_path)
    else:
        with open(mapping_path, "r") as f:
            mapping = json.load(f)

    primary_keys = mapping.get("primary_keys", [])
    column_mappings = mapping.get("column_mappings", [])

    if not primary_keys:
        raise ValueError("Mapping JSON must contain 'primary_keys'.")

    if not column_mappings:
        raise ValueError("Mapping JSON must contain 'column_mappings'.")

    valid_data_types = ["string", "integer", "double", "date", "timestamp", "boolean"]
    for mapping_entry in column_mappings:
        data_type = mapping_entry.get("data_type")

        if data_type:
            if data_type not in valid_data_types:
                raise ValueError(
                    f"Invalid data_type '{data_type}' for column '{mapping_entry.get('target_column')}'. "
                    f"Valid types: {valid_data_types}"
                )

            if data_type in ["date", "timestamp"]:
                if not mapping_entry.get("date_format"):
                    raise ValueError(
                        f"Column '{mapping_entry.get('target_column')}' has data_type '{data_type}' "
                        f"but missing 'date_format' specification."
                    )

    return primary_keys, column_mappings

# ============================================================
# COMPLEX TYPE HANDLING
# ============================================================
def has_nested_structures(df):
    """
    Checks if DataFrame has nested struct/array/map columns.
    """
    for field in df.schema.fields:
        if isinstance(field.dataType, (StructType, ArrayType, MapType)):
            return True
    return False


def flatten_dataframe(df, delimiter="_", max_depth=5):
    """
    Flattens nested struct columns recursively.

    Args:
        df: Spark DataFrame
        delimiter: Separator for flattened column names
        max_depth: Maximum nesting depth to flatten

    Example:
        address.city -> address_city
        address.zip -> address_zip
    """
    def flatten_struct(df, prefix="", depth=0):
        if depth >= max_depth:
            return df

        flat_cols = []
        has_struct = False

        for field in df.schema.fields:
            col_name = field.name
            col_type = field.dataType

            full_col_name = f"{prefix}{delimiter}{col_name}" if prefix else col_name

            if isinstance(col_type, StructType):
                has_struct = True
                # Expand struct fields
                for nested_field in col_type.fields:
                    nested_col_name = f"{full_col_name}{delimiter}{nested_field.name}"
                    flat_cols.append(
                        F.col(f"{col_name}.{nested_field.name}").alias(nested_col_name)
                    )
            elif isinstance(col_type, ArrayType):
                # Convert arrays to JSON strings
                flat_cols.append(F.to_json(F.col(col_name)).alias(full_col_name))
            elif isinstance(col_type, MapType):
                # Convert maps to JSON strings
                flat_cols.append(F.to_json(F.col(col_name)).alias(full_col_name))
            else:
                # Simple types
                flat_cols.append(F.col(col_name).alias(full_col_name))

        df_flat = df.select(*flat_cols)

        # Recursively flatten if there are still struct columns
        if has_struct and depth < max_depth:
            return flatten_struct(df_flat, prefix="", depth=depth + 1)

        return df_flat

    return flatten_struct(df)

# ============================================================
# HELPER FUNCTIONS
# ============================================================
def print_section(title):
    print("\n" + "=" * 110)
    print(title)
    print("=" * 110)


def create_run_output_dir(base_output_dir=OUTPUT_BASE_PATH):
    """
    Creates timestamped run folder:
      output/run_YYYYMMDD_HHMMSS/
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    # run_output_dir = os.path.join(base_output_dir, f"run_{timestamp}")
    run_output_dir = os.path.join(base_output_dir, "run_reconciliation")
    os.makedirs(run_output_dir, exist_ok=True)
    return run_output_dir


def rename_source_columns_to_common_names(source_df, column_mappings):
    """
    Renames source columns to target/common names based on mapping.
    Example:
      source.first_nm -> first_name
    """
    df = source_df
    for mapping in column_mappings:
        source_col = mapping["source_column"]
        target_col = mapping["target_column"]

        if source_col != target_col:
            df = df.withColumnRenamed(source_col, target_col)

    return df


def get_common_primary_keys(primary_keys):
    """
    After source columns are renamed to target/common names,
    primary keys become target/common column names.
    """
    return [pk["target_column"] for pk in primary_keys]

# ============================================================
# BACKUP FUNCTION
# ============================================================
def create_backup(file_path):
    """Creates a timestamped backup of the original file (file targets only)."""
    import shutil

    if not os.path.exists(file_path):
        print(f"[WARNING] Original file not found: {file_path}")
        return None

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    file_dir = os.path.dirname(file_path)
    file_name = os.path.basename(file_path)
    file_name_no_ext, file_ext = os.path.splitext(file_name)

    backup_name = f"{file_name_no_ext}_backup_{timestamp}{file_ext}"
    backup_path = os.path.join(file_dir, backup_name)

    try:
        shutil.copy2(file_path, backup_path)
        print(f"[OK] Backup created: {backup_path}")
        return backup_path
    except Exception as e:
        print(f"[ERROR] Backup failed: {str(e)}")
        return None

# ============================================================
# RECONCILIATION REPORT READER
# ============================================================
def read_reconciliation_report(report_path):
    """Reads the reconciliation Excel report."""
    print_section("READING RECONCILIATION REPORT")
    print(f"Report path: {report_path}")

    try:
        detailed_mismatch_df = pd.read_excel(report_path, sheet_name="detailed_mismatch")
        extra_in_source_df = pd.read_excel(report_path, sheet_name="extra_in_source")
        extra_in_target_df = pd.read_excel(report_path, sheet_name="extra_in_target")
        summary_df = pd.read_excel(report_path, sheet_name="summary_report")

        print(f"[OK] Detailed mismatch records: {len(detailed_mismatch_df)}")
        print(f"[OK] Extra records in source: {len(extra_in_source_df)}")
        print(f"[OK] Extra records in target: {len(extra_in_target_df)}")

        return {
            "detailed_mismatch": detailed_mismatch_df,
            "extra_in_source": extra_in_source_df,
            "extra_in_target": extra_in_target_df,
            "summary": summary_df
        }
    except Exception as e:
        print(f"[ERROR] Failed to read reconciliation report: {str(e)}")
        raise

# ============================================================
# GLUE-SAFE RECONCILIATION REPORT READER
# ============================================================
def read_reconciliation_report_glue(report_path):
    """
    Reads reconciliation Excel report from local path or S3.
    For S3, downloads to /tmp first.
    """
    print_section("READING RECONCILIATION REPORT")
    print(f"Report path: {report_path}")

    local_report_path = report_path

    try:
        if is_s3_path(report_path):
            s3 = boto3.client("s3")
            bucket, key = parse_s3_path(report_path)
            local_report_path = f"/tmp/{os.path.basename(key)}"
            s3.download_file(bucket, key, local_report_path)
            print(f"[INFO] Downloaded report from S3 to: {local_report_path}")

        detailed_mismatch_df = pd.read_excel(local_report_path, sheet_name="detailed_mismatch")
        extra_in_source_df = pd.read_excel(local_report_path, sheet_name="extra_in_source")
        extra_in_target_df = pd.read_excel(local_report_path, sheet_name="extra_in_target")
        summary_df = pd.read_excel(local_report_path, sheet_name="summary_report")

        print(f"[OK] Detailed mismatch records: {len(detailed_mismatch_df)}")
        print(f"[OK] Extra records in source: {len(extra_in_source_df)}")
        print(f"[OK] Extra records in target: {len(extra_in_target_df)}")

        return {
            "detailed_mismatch": detailed_mismatch_df,
            "extra_in_source": extra_in_source_df,
            "extra_in_target": extra_in_target_df,
            "summary": summary_df
        }

    except Exception as e:
        print(f"[ERROR] Failed to read reconciliation report: {str(e)}")
        raise

# ============================================================
# HELPER FUNCTION
# ============================================================
def parse_mismatched_columns(mismatched_columns_str):
    """Parses comma-separated mismatched columns string."""
    if pd.isna(mismatched_columns_str) or mismatched_columns_str == "":
        return []
    return [col.strip() for col in str(mismatched_columns_str).split(",") if col.strip()]

# ============================================================
# OPTIMIZED UPDATE OPERATIONS
# ============================================================
def perform_updates(target_df, source_df, detailed_mismatch_df, primary_key_columns):
    """
    Updates target records based on detailed mismatch information.
    Uses join-based batch updates.
    """
    print_section("PERFORMING UPDATE OPERATIONS")

    if len(detailed_mismatch_df) == 0:
        print("[INFO] No records to update.")
        return target_df, {"total_updates": 0, "updated_records": 0, "updated_columns": {}}

    update_stats = {
        "total_updates": 0,
        "updated_records": 0,
        "updated_columns": {},
        "update_details": []
    }

    print(f"[INFO] Records to update: {len(detailed_mismatch_df)}")

    # Debug: Show what columns exist
    print(f"[DEBUG] Target columns: {sorted(target_df.columns)}")
    print(f"[DEBUG] Source columns: {sorted(source_df.columns)}")

    # Collect all unique columns that need updating
    all_mismatched_cols = set()
    column_update_count = {}

    for idx, row in detailed_mismatch_df.iterrows():
        mismatched_cols = parse_mismatched_columns(row.get("mismatched_columns", ""))
        all_mismatched_cols.update(mismatched_cols)
        for col in mismatched_cols:
            column_update_count[col] = column_update_count.get(col, 0) + 1

    print(f"[INFO] Unique columns to update: {all_mismatched_cols}")
    print(f"[INFO] Column update counts: {column_update_count}")

    # Verify all columns exist in both DataFrames
    target_cols_set = set(target_df.columns)
    source_cols_set = set(source_df.columns)

    missing_in_target = [col for col in all_mismatched_cols if col not in target_cols_set]
    missing_in_source = [col for col in all_mismatched_cols if col not in source_cols_set]

    if missing_in_target:
        print(f"[ERROR] Columns missing in target: {missing_in_target}")
        print("[ERROR] This should not happen if schema enforcement is working correctly!")
        raise ValueError(f"Target missing columns: {missing_in_target}")

    if missing_in_source:
        print(f"[ERROR] Columns missing in source: {missing_in_source}")
        raise ValueError(f"Source missing columns: {missing_in_source}")

    # Convert pandas to Spark for join
    spark = target_df.sparkSession
    mismatch_keys_df = spark.createDataFrame(detailed_mismatch_df[primary_key_columns])

    print(f"[INFO] Converted {len(detailed_mismatch_df)} mismatch keys to Spark DataFrame")

    # Select only needed columns from source
    source_cols_needed = list(primary_key_columns) + list(all_mismatched_cols)
    source_subset = source_df.select(*source_cols_needed)

    # Join source with mismatch keys
    print(f"[INFO] Joining source with mismatch keys...")
    source_correct_values = source_subset.join(
        mismatch_keys_df,
        on=primary_key_columns,
        how="inner"
    )

    # Add suffix to source columns
    for col in source_correct_values.columns:
        if col not in primary_key_columns:
            source_correct_values = source_correct_values.withColumnRenamed(col, f"{col}_src_correct")

    print(f"[INFO] Joining target with correct values...")
    target_with_correct = target_df.join(
        source_correct_values,
        on=primary_key_columns,
        how="left"
    )

    # Update columns
    print(f"[INFO] Updating columns...")
    for col_name in all_mismatched_cols:
        src_col_name = f"{col_name}_src_correct"
        if src_col_name in target_with_correct.columns:
            target_with_correct = target_with_correct.withColumn(
                col_name,
                F.coalesce(F.col(src_col_name), F.col(col_name))
            )
            update_stats["updated_columns"][col_name] = column_update_count.get(col_name, 0)
            print(f"[INFO] Updated column: {col_name}")

    # Drop temporary columns
    updated_target_df = target_with_correct.select(target_df.columns)

    update_stats["updated_records"] = len(detailed_mismatch_df)
    update_stats["total_updates"] = sum(column_update_count.values())

    # Build update details
    detail_limit = min(1000, len(detailed_mismatch_df))
    for idx, row in detailed_mismatch_df.head(detail_limit).iterrows():
        pk_values = {pk_col: row[pk_col] for pk_col in primary_key_columns}
        mismatched_cols = parse_mismatched_columns(row.get("mismatched_columns", ""))
        update_stats["update_details"].append({
            "primary_keys": pk_values,
            "updated_columns": mismatched_cols
        })

        if idx < 10:
            print(f"[OK] Updated record {idx + 1}: PK={pk_values}, Columns={mismatched_cols}")

    if len(detailed_mismatch_df) > 10:
        print(f"[INFO] ... and {len(detailed_mismatch_df) - 10} more records")

    print(f"\n[SUMMARY] Total records updated: {update_stats['updated_records']}")
    print(f"[SUMMARY] Total column updates: {update_stats['total_updates']}")
    print(f"[SUMMARY] Columns updated: {dict(update_stats['updated_columns'])}")

    return updated_target_df, update_stats

# ============================================================
# FIXED INSERT OPERATIONS - ALIGNS COLUMN ORDER
# ============================================================
def perform_inserts(target_df, source_df, extra_in_source_df, primary_key_columns):
    """
    Inserts records from source that are missing in target.
    FIXED: Ensures column order matches target before union.
    """
    print_section("PERFORMING INSERT OPERATIONS")

    if len(extra_in_source_df) == 0:
        print("[INFO] No records to insert.")
        return target_df, {"total_inserts": 0, "insert_details": []}

    insert_stats = {
        "total_inserts": 0,
        "insert_details": []
    }

    print(f"[INFO] Records to insert: {len(extra_in_source_df)}")

    # Convert pandas to Spark
    spark = source_df.sparkSession
    print(f"[INFO] Converting pandas DataFrame to Spark DataFrame...")
    extra_in_source_spark_df = spark.createDataFrame(extra_in_source_df)

    # Join to fetch records
    print(f"[INFO] Joining source with insert keys...")
    records_to_insert = source_df.join(
        extra_in_source_spark_df,
        on=primary_key_columns,
        how="inner"
    )

    # Count
    print(f"[INFO] Counting matched records...")
    insert_count = records_to_insert.count()

    if insert_count == 0:
        print("[WARNING] No matching records found in source.")
        return target_df, insert_stats

    print(f"[INFO] Found {insert_count} records to insert")

    # CRITICAL FIX: Align column order with target
    target_column_order = target_df.columns
    print(f"[DEBUG] Target column order: {target_column_order}")
    print(f"[DEBUG] Source columns before reorder: {records_to_insert.columns}")

    # Select columns in target's order
    records_to_insert_aligned = records_to_insert.select(*target_column_order)

    print(f"[DEBUG] Source columns after reorder: {records_to_insert_aligned.columns}")

    # Union - now both have same column order
    print(f"[INFO] Appending {insert_count} records to target...")
    updated_target_df = target_df.union(records_to_insert_aligned)

    # Build insert details
    detail_limit = min(1000, len(extra_in_source_df))
    pk_values_list = []
    for idx, row in extra_in_source_df.head(detail_limit).iterrows():
        pk_values = {pk_col: row[pk_col] for pk_col in primary_key_columns}
        pk_values_list.append(pk_values)

    insert_stats["total_inserts"] = insert_count
    insert_stats["insert_details"] = pk_values_list
    if len(extra_in_source_df) > detail_limit:
        insert_stats["insert_details_note"] = f"Limited to first {detail_limit} records"

    print(f"[OK] Successfully inserted {insert_count} records.")
    print(f"[SUMMARY] Total records inserted: {insert_stats['total_inserts']}")

    return updated_target_df, insert_stats

# ============================================================
# OPTIMIZED DELETE OPERATIONS
# ============================================================
def perform_deletes(target_df, extra_in_target_df, primary_key_columns):
    """
    Deletes records from target that don't exist in source.
    Uses left_anti join.
    """
    print_section("PERFORMING DELETE OPERATIONS")

    if len(extra_in_target_df) == 0:
        print("[INFO] No records to delete.")
        return target_df, {"total_deletes": 0, "delete_details": []}

    delete_stats = {
        "total_deletes": 0,
        "delete_details": []
    }

    print(f"[INFO] Records to delete: {len(extra_in_target_df)}")

    initial_count = target_df.count()
    print(f"[INFO] Target count before delete: {initial_count}")

    # Convert pandas to Spark
    spark = target_df.sparkSession
    print(f"[INFO] Converting pandas DataFrame to Spark DataFrame...")
    extra_in_target_spark_df = spark.createDataFrame(extra_in_target_df)

    # Left anti join
    print(f"[INFO] Filtering out records to delete...")
    updated_target_df = target_df.join(
        extra_in_target_spark_df,
        on=primary_key_columns,
        how="left_anti"
    )

    print(f"[INFO] Counting remaining records...")
    final_count = updated_target_df.count()
    deleted_count = initial_count - final_count

    print(f"[INFO] Target count after delete: {final_count}")
    print(f"[INFO] Records deleted: {deleted_count}")

    # Build delete details
    detail_limit = min(1000, len(extra_in_target_df))
    pk_values_list = []
    for idx, row in extra_in_target_df.head(detail_limit).iterrows():
        pk_values = {pk_col: row[pk_col] for pk_col in primary_key_columns}
        pk_values_list.append(pk_values)

    delete_stats["total_deletes"] = deleted_count
    delete_stats["delete_details"] = pk_values_list
    if len(extra_in_target_df) > detail_limit:
        delete_stats["delete_details_note"] = f"Limited to first {detail_limit} records"

    print(f"[OK] Successfully deleted {deleted_count} records.")
    print(f"[SUMMARY] Total records deleted: {delete_stats['total_deletes']}")

    return updated_target_df, delete_stats

# ============================================================
# OUTPUT WRITER
# ============================================================

# Code Generated by Sidekick is for learning and experimentation purposes only.

def write_reconciled_target(spark, reconciled_df, output_path, file_format, overwrite_original=False):
    """
    Writes the reconciled target DataFrame to file.
    Respects data types from the original Spark schema (which comes from mapping).
    ENHANCED: Proper NULL handling for all formats (JSON, CSV, Parquet, Excel).
    Supports local output path.
    """
    print_section("WRITING RECONCILED TARGET FILE")

    if overwrite_original:
        print("[INFO] Overwrite mode: Will replace original target file")
    else:
        print("[INFO] Safe mode: Creating new reconciled file")

    print(f"Output path: {output_path}")
    print(f"File format: {file_format}")

    try:
        from pyspark.sql.types import IntegerType, LongType, ShortType, ByteType, DateType, TimestampType

        # Store schema - this comes from your mapping JSON
        original_schema = reconciled_df.schema

        # Identify integer columns from schema (as defined in mapping)
        integer_columns = [
            field.name for field in original_schema.fields
            if isinstance(field.dataType, (IntegerType, LongType, ShortType, ByteType))
        ]

        if integer_columns:
            print(f"[INFO] Integer columns from mapping: {integer_columns}")

        # Prepare dates for JSON/CSV export
        if file_format in ["json", "csv"]:
            print("[INFO] Converting date columns to strings for export...")

            for field in original_schema.fields:
                if isinstance(field.dataType, DateType):
                    reconciled_df = reconciled_df.withColumn(
                        field.name,
                        F.when(
                            F.col(field.name).isNull(),
                            F.lit(None)
                        ).otherwise(
                            F.date_format(F.col(field.name), "M/d/yyyy")
                        )
                    )
                elif isinstance(field.dataType, TimestampType):
                    reconciled_df = reconciled_df.withColumn(
                        field.name,
                        F.when(
                            F.col(field.name).isNull(),
                            F.lit(None)
                        ).otherwise(
                            F.date_format(F.col(field.name), "yyyy-MM-dd HH:mm:ss")
                        )
                    )

        # Convert to pandas
        print("[INFO] Converting Spark DataFrame to Pandas...")
        pandas_df = reconciled_df.toPandas()
        record_count = len(pandas_df)
        print(f"[INFO] Records to write: {record_count}")

        # CRITICAL FIX: Replace NaN with None for proper NULL handling
        print("[INFO] Cleaning NaN values...")
        pandas_df = pandas_df.where(pd.notnull(pandas_df), None)

        # Create output directory
        output_dir = os.path.dirname(output_path)
        if output_dir:  # Only create if there's a directory path
            os.makedirs(output_dir, exist_ok=True)

        # ============================================================
        # JSON FORMAT - NULL as 'null'
        # ============================================================
        if file_format == "json":
            import json

            print("[INFO] Preparing JSON output with proper NULL handling...")

            # Convert integer columns to Int64 (nullable integer) based on mapping
            if integer_columns:
                print("[INFO] Converting integer columns to preserve type in JSON...")
                for col in integer_columns:
                    if col in pandas_df.columns:
                        # Use Int64 which supports NaN -> None conversion
                        pandas_df[col] = pandas_df[col].astype('Int64')
                        # Replace pd.NA with None for JSON serialization
                        pandas_df[col] = pandas_df[col].apply(lambda x: None if pd.isna(x) else x)

            # Convert to records
            records = pandas_df.to_dict(orient='records')

            # Additional cleanup: ensure None instead of NaN in records
            for record in records:
                for key, value in record.items():
                    if pd.isna(value):
                        record[key] = None

            # Write JSON with proper null values
            with open(output_path, 'w') as f:
                json.dump(records, f, indent=2, default=str)

            print(f"[OK] JSON written with NULL as 'null': {output_path}")

        # ============================================================
        # CSV FORMAT - NULL as empty string
        # ============================================================
        elif file_format == "csv":
            print("[INFO] Preparing CSV output with empty strings for NULL...")

            # For CSV, replace None with empty string for cleaner output
            pandas_df_csv = pandas_df.fillna('')
            pandas_df_csv.to_csv(output_path, index=False, na_rep='')

            print(f"[OK] CSV written with NULL as empty string: {output_path}")

        # ============================================================
        # PARQUET FORMAT - Native NULL support
        # ============================================================
        elif file_format == "parquet":
            print("[INFO] Preparing Parquet output with native NULL support...")

            # Parquet has native NULL support, no conversion needed
            # Just ensure proper data types
            try:
                pandas_df.to_parquet(output_path, index=False, engine='pyarrow')
                print(f"[OK] Parquet written with native NULL values: {output_path}")
            except ImportError:
                print("[WARNING] PyArrow not installed, using fastparquet...")
                pandas_df.to_parquet(output_path, index=False, engine='fastparquet')
                print(f"[OK] Parquet written with native NULL values: {output_path}")

        # ============================================================
        # EXCEL FORMAT - NULL as empty cell
        # ============================================================
        elif file_format == "excel":
            print("[INFO] Preparing Excel output with empty cells for NULL...")

            # openpyxl automatically converts None to empty cells
            pandas_df_excel = pandas_df.copy()
            pandas_df_excel.to_excel(output_path, index=False, engine="openpyxl", na_rep='')

            print(f"[OK] Excel written with NULL as empty cells: {output_path}")

        else:
            raise ValueError(f"Unsupported file format: {file_format}")

        # Verify file created
        if os.path.exists(output_path):
            file_size = os.path.getsize(output_path) / (1024 * 1024)
            print(f"[OK] File created: {file_size:.2f} MB")

            # Print NULL handling info
            null_counts = pandas_df.isnull().sum()
            total_nulls = null_counts.sum()
            if total_nulls > 0:
                print(f"[INFO] Total NULL values written: {total_nulls}")
                print(f"[INFO] NULL values by column:")
                for col, count in null_counts[null_counts > 0].items():
                    print(f"       {col}: {count}")
        else:
            raise FileNotFoundError(f"Output file not created: {output_path}")

    except Exception as e:
        print(f"[ERROR] Failed to write: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

# ============================================================
# GLUE-SAFE OUTPUT WRITER
# ============================================================
def write_reconciled_target_glue(spark, reconciled_df, output_path, file_format, overwrite_original=False):
    """
    Glue-safe wrapper around existing write logic.
    Writes to local temp if output is S3, then uploads to S3.
    """
    if not is_s3_path(output_path):
        return write_reconciled_target(spark, reconciled_df, output_path, file_format, overwrite_original)

    # S3 target -> write to /tmp first
    local_tmp_file = f"/tmp/{os.path.basename(output_path)}"
    print(f"[INFO] S3 output detected. Writing locally first: {local_tmp_file}")

    # Reuse existing writer
    write_reconciled_target(spark, reconciled_df, local_tmp_file, file_format, overwrite_original=False)

    # Upload to S3
    s3 = boto3.client("s3")
    bucket, key = parse_s3_path(output_path)
    s3.upload_file(local_tmp_file, bucket, key)

    print(f"[OK] Uploaded reconciled target to S3: {output_path}")



def write_dynamodb_table(glueContext, df, table_name):
    """
    Writes Spark DataFrame to DynamoDB table.
    NOTE:
      - DynamoDB write behaves like upsert based on table keys
      - It does NOT delete old extra items automatically
    """
    print(f"\n[INFO] Writing reconciled output to DynamoDB table: {table_name}")

    dyf = DynamicFrame.fromDF(df, glueContext, "reconciled_dyf")

    glueContext.write_dynamic_frame.from_options(
        frame=dyf,
        connection_type="dynamodb",
        connection_options={
            "dynamodb.output.tableName": table_name,
            "dynamodb.throughput.write.percent": "0.5"
        }
    )

    print(f"[OK] Reconciled output written to DynamoDB: {table_name}")


def write_target_smart(glueContext, spark, reconciled_df, output_path, file_format, overwrite_original=False):
    """
    Writes reconciled target either to:
      - DynamoDB table (dynamodb:table_name)
      - File path using existing file write logic
    """
    if is_dynamodb_path(output_path):
        table_name = extract_dynamodb_table_name(output_path)
        write_dynamodb_table(glueContext, reconciled_df, table_name)
        return

    write_reconciled_target_glue(
        spark, reconciled_df, output_path, file_format, overwrite_original
    )
# ============================================================
# SUMMARY REPORT
# ============================================================
def generate_reconciliation_summary_report(
    run_output_dir, update_stats, insert_stats, delete_stats,
    initial_target_count, final_target_count
):
    """Generates comprehensive summary report."""
    print_section("GENERATING RECONCILIATION SUMMARY REPORT")

    summary_data = {
        "reconciliation_timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "initial_target_count": initial_target_count,
        "final_target_count": final_target_count,
        "total_updates": update_stats["updated_records"],
        "total_column_updates": update_stats["total_updates"],
        "total_inserts": insert_stats["total_inserts"],
        "total_deletes": delete_stats["total_deletes"],
        "net_change": final_target_count - initial_target_count
    }

    summary_df = pd.DataFrame([summary_data])
    update_details_df = pd.DataFrame(update_stats.get("update_details", []))
    insert_details_df = pd.DataFrame(insert_stats.get("insert_details", []))
    delete_details_df = pd.DataFrame(delete_stats.get("delete_details", []))

    column_updates = update_stats.get("updated_columns", {})
    column_update_df = pd.DataFrame([
        {"column_name": col, "update_count": count}
        for col, count in column_updates.items()
    ])

    excel_path = os.path.join(run_output_dir, "reconciliation_summary.xlsx")

    with pd.ExcelWriter(excel_path, engine="openpyxl") as writer:
        summary_df.to_excel(writer, sheet_name="summary", index=False)
        update_details_df.to_excel(writer, sheet_name="update_details", index=False)
        column_update_df.to_excel(writer, sheet_name="column_updates", index=False)
        insert_details_df.to_excel(writer, sheet_name="insert_details", index=False)
        delete_details_df.to_excel(writer, sheet_name="delete_details", index=False)

    print(f"[OK] Reconciliation summary report: {excel_path}")

    print("\n" + "=" * 110)
    print("RECONCILIATION SUMMARY")
    print("=" * 110)
    print(f"Initial target record count: {initial_target_count}")
    print(f"Records updated: {update_stats['updated_records']}")
    print(f"Column updates performed: {update_stats['total_updates']}")
    print(f"Records inserted: {insert_stats['total_inserts']}")
    print(f"Records deleted: {delete_stats['total_deletes']}")
    print(f"Final target record count: {final_target_count}")
    print(f"Net change: {final_target_count - initial_target_count:+d}")
    print("=" * 110)

    return excel_path

# ============================================================
# GLUE-SAFE SUMMARY REPORT WRITER
# ============================================================
def generate_reconciliation_summary_report_glue(
    run_output_dir, update_stats, insert_stats, delete_stats,
    initial_target_count, final_target_count
):
    """
    Glue-safe wrapper for summary report.
    Writes locally first if run_output_dir is S3, then uploads.
    """
    if not is_s3_path(run_output_dir):
        return generate_reconciliation_summary_report(
            run_output_dir, update_stats, insert_stats, delete_stats,
            initial_target_count, final_target_count
        )

    local_tmp_dir = "/tmp/reconciliation_summary_output"
    os.makedirs(local_tmp_dir, exist_ok=True)

    local_excel_path = generate_reconciliation_summary_report(
        local_tmp_dir, update_stats, insert_stats, delete_stats,
        initial_target_count, final_target_count
    )

    final_s3_path = f"{run_output_dir.rstrip('/')}/reconciliation_summary.xlsx"
    s3 = boto3.client("s3")
    bucket, key = parse_s3_path(final_s3_path)
    s3.upload_file(local_excel_path, bucket, key)

    print(f"[OK] Uploaded summary report to S3: {final_s3_path}")
    return final_s3_path

# ============================================================
# LOCAL MAIN
# ============================================================
def main():
    """Main reconciliation workflow for local execution."""
    spark = create_spark_session("Data Reconciliation Job")

    run_output_dir = create_run_output_dir(OUTPUT_BASE_PATH)
    print_section("RECONCILIATION RUN DIRECTORY")
    print(f"Output directory: {run_output_dir}")

    backup_path = None

    try:
        # Read reconciliation report
        report_data = read_reconciliation_report(RECONCILIATION_REPORT_PATH)
        detailed_mismatch_df = report_data["detailed_mismatch"]
        extra_in_source_df = report_data["extra_in_source"]
        extra_in_target_df = report_data["extra_in_target"]

        # Read mapping
        print_section("READING MAPPING JSON")
        primary_keys, column_mappings = read_mapping_json(MAPPING_PATH)
        primary_key_columns = get_common_primary_keys(primary_keys)
        print(f"Primary key columns: {primary_key_columns}")

        # Backup if needed
        if OVERWRITE_ORIGINAL_TARGET and CREATE_BACKUP:
            print_section("CREATING BACKUP")
            backup_path = create_backup(TARGET_PATH)

        # Load files using YOUR validation script's functions
        print_section("LOADING SOURCE AND TARGET FILES")

        source_df = read_source_smart(
            spark, SOURCE_PATH,
            column_mappings=column_mappings,
            dataset_name="source",
            **FILE_CONFIG["source"]
        )
        source_df = rename_source_columns_to_common_names(source_df, column_mappings)
        print(f"Source records: {source_df.count()}")
        print(f"Source columns: {sorted(source_df.columns)}")

        if is_dynamodb_path(TARGET_PATH):
            raise ValueError("Local main() does not support DynamoDB target writes. Use main_glue() in AWS Glue for DynamoDB source/target.")
        target_df = read_file_smart(
            spark, TARGET_PATH,
            column_mappings=column_mappings,
            dataset_name="target",
            **FILE_CONFIG["target"]
        )
        initial_target_count = target_df.count()
        print(f"Target records (initial): {initial_target_count}")
        print(f"Target columns: {sorted(target_df.columns)}")

        # Perform operations
        target_df, update_stats = perform_updates(
            target_df, source_df, detailed_mismatch_df, primary_key_columns
        )

        target_df, insert_stats = perform_inserts(
            target_df, source_df, extra_in_source_df, primary_key_columns
        )

        target_df, delete_stats = perform_deletes(
            target_df, extra_in_target_df, primary_key_columns
        )

        final_target_count = target_df.count()
        print(f"\n[INFO] Final target count: {final_target_count}")

        # Output
        target_format = detect_file_format(TARGET_PATH)

        if OVERWRITE_ORIGINAL_TARGET:
            reconciled_output_path = TARGET_PATH
            print(f"\n[WARNING] Will overwrite original: {TARGET_PATH}")
            if backup_path:
                print(f"[INFO] Backup saved: {backup_path}")
        else:
            file_extension = os.path.splitext(TARGET_PATH)[1][1:]
            reconciled_output_path = os.path.join(run_output_dir, f"reconciled_target.{file_extension}")
            print(f"\n[INFO] Creating new file: {reconciled_output_path}")

        write_reconciled_target(spark, target_df, reconciled_output_path, target_format, OVERWRITE_ORIGINAL_TARGET)

        summary_report_path = generate_reconciliation_summary_report(
            run_output_dir, update_stats, insert_stats, delete_stats,
            initial_target_count, final_target_count
        )

        print_section("RECONCILIATION COMPLETE")
        print(f"✓ Reconciled target: {reconciled_output_path}")
        print(f"✓ Summary report: {summary_report_path}")
        if backup_path:
            print(f"✓ Backup: {backup_path}")

        print("\n✓ Reconciliation completed successfully!")

    except Exception as e:
        print(f"\n[ERROR] Reconciliation failed: {str(e)}")
        import traceback
        traceback.print_exc()

        if backup_path:
            print(f"\n[INFO] Backup available: {backup_path}")

    finally:
        spark.stop()

# ============================================================
# GLUE MAIN
# ============================================================
def main_glue():
    """
    AWS Glue entry point.
    Uses job parameters instead of hardcoded local paths.
    """
    required_args = [
        "JOB_NAME",
        "SOURCE_PATH",
        "TARGET_PATH",
        "MAPPING_PATH",
        "RECONCILIATION_REPORT_PATH",
        "OUTPUT_BASE_PATH",
        "SNS_TOPIC_PATH"
    ]

    optional_args = ["OVERWRITE_ORIGINAL_TARGET", "CREATE_BACKUP"]

    # Build list of args actually passed
    passed_args = []
    argv_str = " ".join(sys.argv)

    for arg in required_args:
        if f"--{arg}" not in argv_str:
            raise ValueError(f"Missing required Glue argument: --{arg}")
        passed_args.append(arg)

    for arg in optional_args:
        if f"--{arg}" in argv_str:
            passed_args.append(arg)

    args = getResolvedOptions(sys.argv, passed_args)

    job_name = args["JOB_NAME"]
    source_path = args["SOURCE_PATH"]
    target_path = args["TARGET_PATH"]
    mapping_path = args["MAPPING_PATH"]
    reconciliation_report_path = args["RECONCILIATION_REPORT_PATH"]
    output_base_path = args["OUTPUT_BASE_PATH"]
    SNS_TOPIC_PATH = args["SNS_TOPIC_PATH"]

    overwrite_original_target = args.get("OVERWRITE_ORIGINAL_TARGET", str(OVERWRITE_ORIGINAL_TARGET)).lower() == "true"
    create_backup_flag = args.get("CREATE_BACKUP", str(CREATE_BACKUP)).lower() == "true"

    glueContext, spark, job = create_glue_session(job_name, args)

    run_output_dir = create_run_output_dir_glue(output_base_path)
    print_section("RECONCILIATION RUN DIRECTORY")
    print(f"Output directory: {run_output_dir}")

    backup_path = None

    try:
        # Read reconciliation report
        report_data = read_reconciliation_report_glue(reconciliation_report_path)
        detailed_mismatch_df = report_data["detailed_mismatch"]
        extra_in_source_df = report_data["extra_in_source"]
        extra_in_target_df = report_data["extra_in_target"]

        # Read mapping
        print_section("READING MAPPING JSON")
        primary_keys, column_mappings = read_mapping_json_glue(mapping_path)
        primary_key_columns = get_common_primary_keys(primary_keys)
        print(f"Primary key columns: {primary_key_columns}")

        # Backup if needed (local only)
        if overwrite_original_target and create_backup_flag and not is_s3_path(target_path):
            print_section("CREATING BACKUP")
            backup_path = create_backup(target_path)

        # Load files
        print_section("LOADING SOURCE AND TARGET FILES")

        source_df = read_source_smart(
            glueContext,
            spark, source_path,
            column_mappings=column_mappings,
            dataset_name="source",
            **FILE_CONFIG["source"]
        )
        source_df = rename_source_columns_to_common_names(source_df, column_mappings)
        print(f"Source records: {source_df.count()}")
        print(f"Source columns: {sorted(source_df.columns)}")

        target_df = read_target_smart(
            glueContext,
            spark, target_path,
            column_mappings=column_mappings,
            dataset_name="target",
            **FILE_CONFIG["target"]
        )
        initial_target_count = target_df.count()
        print(f"Target records (initial): {initial_target_count}")
        print(f"Target columns: {sorted(target_df.columns)}")

        # Perform operations
        target_df, update_stats = perform_updates(
            target_df, source_df, detailed_mismatch_df, primary_key_columns
        )

        target_df, insert_stats = perform_inserts(
            target_df, source_df, extra_in_source_df, primary_key_columns
        )

        target_df, delete_stats = perform_deletes(
            target_df, extra_in_target_df, primary_key_columns
        )

        final_target_count = target_df.count()
        print(f"\n[INFO] Final target count: {final_target_count}")

        # Output
        target_format = detect_input_format(target_path)

        if is_dynamodb_path(target_path):
            if overwrite_original_target:
                reconciled_output_path = target_path
                print(f"\n[WARNING] Will upsert into original DynamoDB target: {target_path}")
                print("[WARNING] DynamoDB writes are UPSERTS; old extra items are not auto-deleted.")
            else:
                target_table_name = extract_dynamodb_table_name(target_path)
                reconciled_output_path = f"dynamodb:{target_table_name}_reconciled"
                print(f"\n[INFO] Safe mode for DynamoDB target. Writing to new table reference: {reconciled_output_path}")
                print("[INFO] Ensure the reconciled DynamoDB table already exists before running.")
        else:
            if overwrite_original_target:
                reconciled_output_path = target_path
                print(f"\n[WARNING] Will overwrite original: {target_path}")
                if backup_path:
                    print(f"[INFO] Backup saved: {backup_path}")
            else:
                file_extension = os.path.splitext(target_path)[1][1:]
                reconciled_output_path = f"{run_output_dir.rstrip('/')}/reconciled_target.{file_extension}"
                print(f"\n[INFO] Creating new file: {reconciled_output_path}")

        write_target_smart(
            glueContext, spark, target_df, reconciled_output_path, target_format, overwrite_original_target
        )

        summary_report_path = generate_reconciliation_summary_report_glue(
            run_output_dir, update_stats, insert_stats, delete_stats,
            initial_target_count, final_target_count
        )

        print_section("RECONCILIATION COMPLETE")
        print(f"✓ Reconciled target: {reconciled_output_path}")
        print(f"✓ Summary report: {summary_report_path}")
        if backup_path:
            print(f"✓ Backup: {backup_path}")

        print("\n✓ Reconciliation completed successfully!")

        # Code Generated by Sidekick is for learning and experimentation purposes only.

        # ============================================================
        # SNS NOTIFICATION
        # ============================================================

        # Code Generated by Sidekick is for learning and experimentation purposes only.

        print_section("SENDING SNS NOTIFICATION")

        try:
            # Extract bucket name and report key from the Excel S3 path
            # excel_s3_path format: s3://bucket-name/output/run_YYYYMMDD_HHMMSS/reconciliation_report.xlsx
            bucket_name, report_key = parse_s3_path("s3://etl-valid-recon-framework-s3/reports/reconciliation/run_reconciliation/reconciliation_summary.xlsx")

            print(f"Bucket: {bucket_name}")
            print(f"Report Key: {report_key}")

            # Generate pre-signed URL (1 hour expiration)
            s3_client = boto3.client(
                's3',
                config=Config(signature_version='s3v4')
            )
            
            # FIX: Use s3_client (not s3)
            presigned_url = s3_client.generate_presigned_url(
                "get_object",
                Params={"Bucket": bucket_name, "Key": report_key},
                ExpiresIn=3600
            )

            print(f"Pre-signed URL generated successfully")

            # Build notification message
            message = f"""
        ETL Reconciliation Report is ready.


        Download Full Report:
        {presigned_url}

        Note: This secure link expires in 1 hour.
        """

            # Publish to SNS topic
            sns = boto3.client("sns")
            response = sns.publish(
                TopicArn=SNS_TOPIC_PATH,
                Subject=f"ETL Reconciliation Report Ready",
                Message=message
            )

            print(f"[OK] SNS notification sent successfully. MessageId: {response['MessageId']}")

        except ClientError as e:
            print(f"[ERROR] SNS notification failed due to AWS client error: {str(e)}")
            print(f"Error Code: {e.response['Error']['Code']}")

        except Exception as e:
            print(f"[ERROR] Unexpected error while sending notification: {str(e)}")
            import traceback
            traceback.print_exc()



        job.commit()

    except Exception as e:
        print(f"\n[ERROR] Reconciliation failed: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

    finally:
        spark.stop()

# ============================================================
# ENTRY POINT
# ============================================================
if __name__ == "__main__":
    # If running inside AWS Glue, JOB_NAME will be passed
    if "--JOB_NAME" in sys.argv:
        main_glue()
    else:
        main(

# ============================================================
# DYNAMODB READERS
# ============================================================
def read_dynamodb_table(glueContext, table_name, schema=None):
    """
    Reads DynamoDB table into Spark DataFrame.
    If schema is provided, applies column selection and casting after read.
    """
    print(f"\n[INFO] Reading DynamoDB table: {table_name}")

    dyf = glueContext.create_dynamic_frame.from_options(
        connection_type="dynamodb",
        connection_options={
            "dynamodb.input.tableName": table_name,
            "dynamodb.throughput.read.percent": "0.5"
        }
    )

    df = dyf.toDF()

    if schema:
        existing_cols = set(df.columns)

        select_exprs = []
        missing_cols = []

        for field in schema.fields:
            if field.name in existing_cols:
                select_exprs.append(
                    col(field.name).cast(field.dataType.simpleString()).alias(field.name)
                )
            else:
                missing_cols.append(field.name)

        if missing_cols:
            print(f"[WARN] Missing expected columns in DynamoDB table: {missing_cols}")

        if select_exprs:
            df = df.select(*select_exprs)

    return df


def read_source_smart(glueContext, spark, source_path, column_mappings, dataset_name, **kwargs):
    """
    Reads source either from:
      - DynamoDB table (dynamodb:table_name)
      - File path (csv/json/parquet/xlsx)
    """
    if is_dynamodb_path(source_path):
        table_name = extract_dynamodb_table_name(source_path)
        source_schema = build_schema_from_mapping(column_mappings, dataset_name="source")
        df = read_dynamodb_table(glueContext, table_name, schema=source_schema)
        df = apply_custom_date_formats(df, column_mappings, dataset_name="source")
        return df

    return read_file_smart(
        spark,
        source_path,
        column_mappings=column_mappings,
        dataset_name=dataset_name,
        **kwargs
    )


def read_target_smart(glueContext, spark, target_path, column_mappings, dataset_name, **kwargs):
    """
    Reads target either from:
      - DynamoDB table (dynamodb:table_name)
      - File path (csv/json/parquet/xlsx)
    """
    if is_dynamodb_path(target_path):
        table_name = extract_dynamodb_table_name(target_path)
        target_schema = build_schema_from_mapping(column_mappings, dataset_name="target")
        df = read_dynamodb_table(glueContext, table_name, schema=target_schema)
        df = apply_custom_date_formats(df, column_mappings, dataset_name="target")
        return df

    return read_file_smart(
        spark,
        target_path,
        column_mappings=column_mappings,
        dataset_name=dataset_name,
        **kwargs
    )
)